version: '3.4'

networks: 
    traefik:
        external: true

services:
    traefik:
        image: traefik:alpine
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/etc/traefik/traefik.toml
            - ./acme:/root/acme

        networks: 
            - traefik
        
            
