defaultEntryPoints = ["http", "https"]
logLevel = "INFO"

[docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false
    watch = true

#[api]
#    dashboard = true
#    entrypoint = "dashboard"

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
         [entryPoints.https.tls]
    [entryPoints.dashboard]
    address = ":8080"

[acme]
    storage = "/root/acme/"
    entryPoint = "https"
    onHostRule = true
    email = "comercial@locness.com.br"
    #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
    caServer = "https://acme-v02.api.letsencrypt.org/directory"

    [acme.httpChallenge]
        entryPoint = "http"
