entryPoints:
    web:
      address: ":80"
  
    websecure:
      address: ":443"
  
  certificatesResolvers:
    default:
      acme:
        email: comercial@locness.com.br
        storage: /root/acme.json
        httpChallenge:
          # used during the challenge
          entryPoint: web